### ISSUE TITLE
CWD cleared when clearing the terminal

### ISSUE THREAD

**Issue by syropian** [mattgreen/lucid.fish#17]
I really enjoy the prompt starting on a new line but when you clear the terminal it clears the line with the current working directory and git status and only shows the second line. No idea if there's a way around this, but figured I'd mention it!

**Comment by mattgreen** [comment]
That's odd. I'm unable to replicate this. I use iTerm 3.4.6. When I hit control-L, the screen is cleared and the prompt is displayed as expected. Does it occur with a default prompt?
