### ISSUE TITLE
Add VI mode indicator

### ISSUE THREAD

**Issue by Flygrounder** [mattgreen/lucid.fish#2]
I like the prompt a lot, but as a user of ` fish_vi_key_bindings` it is confusing that I cannot see which mode is on. Indicator would be very helpful.

**Comment by mattgreen** [comment]
You have a few options here, in increasing levels of committment:

1. Add it to the right prompt. lucid.fish doesn't touch the right prompt for this reason, keeping it open for ephemeral status indicators such as current mode
2. Fork and add it to the left prompt as desired
3. Submit a PR for it, which defaults it to off

HTH!
