### ISSUE TITLE
Previous fish_prompt.fish is erased without warning

### ISSUE THREAD

**Issue by joallard** [mattgreen/lucid.fish#6]
I tried this over the past few days, and then I found out that my original Fish prompt (`.config/fish/functions/fish_prompt.fish`) that I had carefully written and tweaked was just gone. Fortunately, I had a backup, but I don't much like it for packages to erase my files without asking me.

**Comment by mattgreen** [comment]
Sorry this happened!

Did you install it via Fisher by any chance?

**Comment by joallard** [comment]
I did! Sorry for not specifying.

**Comment by mattgreen** [comment]
Okay, I see two things that need to happen.

1. I'll file an issue with fisher referencing this issue.
2. I'll update the README to mention this, as it is too easy to get excited about a prompt, try it, and realize you might've liked the old one a little bit more.

**Comment by joallard** [comment]
Sounds like that's exactly what's needed. Thank you for this very proactive response, I really appreciate!

**Comment by jorgebucaran** [comment]
> Fisher expands plugins into your fish configuration directory by default, overwriting existing files. If you wish to change this behavior, set `$fisher_path` to your preferred location and put it in your function path.

Of course, I don't really recommend setting `$fisher_path`, as that, for me, defeats the simplicity of using Fisher. 

By the way, a way to prevent this with current Fisher would be for @joallard's prompt to be installed as a plugin (locally or remotely), rather than untracked file in their `$__fish_config_dir_/functions`.

**Comment by jorgebucaran** [comment]
This is also promising:

> [We could copy any existing prompt files somewhere, and restore them after you uninstall the prompt.](https://github.com/jorgebucaran/fisher/issues/624#issuecomment-728666247)
