### ISSUE TITLE
Use new screenshot as the Social Preview image

### ISSUE THREAD

**Issue by jorgebucaran** [mattgreen/lucid.fish#8]
Because we're still using the old one. 😄 

You can download the [new screenshot here](https://user-images.githubusercontent.com/56996/98549007-9520be80-22dd-11eb-884f-b688c9fd26cf.png) and upload it in [Settings → **Social preview**: Edit ✎](https://github.com/mattgreen/lucid.fish/settings).

![](https://user-images.githubusercontent.com/56996/100550499-a39b3e00-32bd-11eb-81c4-ca44872ab659.png)

**Comment by jorgebucaran** [comment]
Closing as it has been almost a month and nothing was done.

**Comment by mattgreen** [comment]
Forgot to follow up on this. I put it up but am not sure if it displays properly because I don't do social media.

I'm fine with leaving it as is and I'll fix it if someone speaks up. Thanks for the PR.

**Comment by jorgebucaran** [comment]
I think it worked! 😉
